// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: service/rpc-video-operator/videoOperator.proto

package videoOperatorPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoUploadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Data  []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *VideoUploadReq) Reset() {
	*x = VideoUploadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_rpc_video_operator_videoOperator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoUploadReq) ProtoMessage() {}

func (x *VideoUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_rpc_video_operator_videoOperator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoUploadReq.ProtoReflect.Descriptor instead.
func (*VideoUploadReq) Descriptor() ([]byte, []int) {
	return file_service_rpc_video_operator_videoOperator_proto_rawDescGZIP(), []int{0}
}

func (x *VideoUploadReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *VideoUploadReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VideoUploadReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type VideoUploadResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	StatusMsg string `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
}

func (x *VideoUploadResp) Reset() {
	*x = VideoUploadResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_rpc_video_operator_videoOperator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoUploadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoUploadResp) ProtoMessage() {}

func (x *VideoUploadResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_rpc_video_operator_videoOperator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoUploadResp.ProtoReflect.Descriptor instead.
func (*VideoUploadResp) Descriptor() ([]byte, []int) {
	return file_service_rpc_video_operator_videoOperator_proto_rawDescGZIP(), []int{1}
}

func (x *VideoUploadResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VideoUploadResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

var File_service_rpc_video_operator_videoOperator_proto protoreflect.FileDescriptor

var file_service_rpc_video_operator_videoOperator_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2d, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x50,
	0x62, 0x22, 0x50, 0x0a, 0x0e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x22, 0x48, 0x0a, 0x0f, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x73, 0x67, 0x32, 0x5c, 0x0a,
	0x0d, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x4b,
	0x0a, 0x06, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1f, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x50, 0x62, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x76, 0x69, 0x64, 0x65,
	0x6f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x50, 0x62, 0x2e, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x42, 0x13, 0x5a, 0x11, 0x2e,
	0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x50, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_rpc_video_operator_videoOperator_proto_rawDescOnce sync.Once
	file_service_rpc_video_operator_videoOperator_proto_rawDescData = file_service_rpc_video_operator_videoOperator_proto_rawDesc
)

func file_service_rpc_video_operator_videoOperator_proto_rawDescGZIP() []byte {
	file_service_rpc_video_operator_videoOperator_proto_rawDescOnce.Do(func() {
		file_service_rpc_video_operator_videoOperator_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_rpc_video_operator_videoOperator_proto_rawDescData)
	})
	return file_service_rpc_video_operator_videoOperator_proto_rawDescData
}

var file_service_rpc_video_operator_videoOperator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_rpc_video_operator_videoOperator_proto_goTypes = []interface{}{
	(*VideoUploadReq)(nil),  // 0: videoOperatorPb.VideoUploadReq
	(*VideoUploadResp)(nil), // 1: videoOperatorPb.VideoUploadResp
}
var file_service_rpc_video_operator_videoOperator_proto_depIdxs = []int32{
	0, // 0: videoOperatorPb.VideoOperator.Upload:input_type -> videoOperatorPb.VideoUploadReq
	1, // 1: videoOperatorPb.VideoOperator.Upload:output_type -> videoOperatorPb.VideoUploadResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_rpc_video_operator_videoOperator_proto_init() }
func file_service_rpc_video_operator_videoOperator_proto_init() {
	if File_service_rpc_video_operator_videoOperator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_rpc_video_operator_videoOperator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoUploadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_rpc_video_operator_videoOperator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoUploadResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_rpc_video_operator_videoOperator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_rpc_video_operator_videoOperator_proto_goTypes,
		DependencyIndexes: file_service_rpc_video_operator_videoOperator_proto_depIdxs,
		MessageInfos:      file_service_rpc_video_operator_videoOperator_proto_msgTypes,
	}.Build()
	File_service_rpc_video_operator_videoOperator_proto = out.File
	file_service_rpc_video_operator_videoOperator_proto_rawDesc = nil
	file_service_rpc_video_operator_videoOperator_proto_goTypes = nil
	file_service_rpc_video_operator_videoOperator_proto_depIdxs = nil
}
