
stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  tags:
    - go-test
  stage: build
  script:
    - go build -o ./build/dy-api-gateway ./service/api-gateway/.
    - go build -o ./build/dy-user-info ./service/rpc-user-info/.
    - go build -o ./build/dy-user-comm ./service/rpc-user-operator/rpc-user-comment/.
    - go build -o ./build/dy-user-favo ./service/rpc-user-operator/rpc-user-favo/.
    - go build -o ./build/dy-user-relation ./service/rpc-user-relation/.
    - go build -o ./build/dy-video ./service/rpc-video-operator/.


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - ps -ef | grep go | grep build | awk '{print "kill "$2}' | sh
    - ./build/dy-api-gateway
    - ./build/dy-user-info
    - ./build/dy-user-comm
    - ./build/dy-user-favo
    - ./build/dy-user-relation
    - ./build/dy-video
