
stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  tags:
    - go-test
  stage: build
  script:
    - go build -o /home/dy-build/dy-api-gateway ./service/api-gateway/.
    - go build -o /home/dy-build/dy-user-info ./service/rpc-user-info/.
    - go build -o /home/dy-build/dy-user-comm ./service/rpc-user-operator/rpc-user-comment/.
    - go build -o /home/dy-build/dy-user-favo ./service/rpc-user-operator/rpc-user-favo/.
    - go build -o /home/dy-build/dy-user-relation ./service/rpc-user-relation/.
    - go build -o /home/dy-build/dy-video ./service/rpc-video-operator/.


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - (ps -ef | grep go | grep build | grep -v grep | awk '{print "kill "$2}' | sh) && true=0 || false=1
    - /home/dy-build/dy-api-gateway &
    - /home/dy-build/dy-user-info &
    - /home/dy-build/dy-user-comm &
    - /home/dy-build/dy-user-favo &
    - /home/dy-build/dy-user-relation &
    - /home/dy-build/dy-video &
    - echo Finish
    - exit 0
