// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"paigu1902/douyin/service/api-gateway/router"
)

func main() {
	// TODO:暂时没有研究hertz将网关也注册上去
	svr := server.New(
		server.WithHostPorts(":3002"),
		//server.WithRegistry(r),
	)
	router.Register(svr)
	//v1 := svr.Group("/v1")
	//v1.POST("/login", userInfo.LoginMethod)
	//v1.POST("/register", userInfo.RegisterMethod)
	//v2 := svr.Group("/v2")
	//v2.Use(middlewares.AuthUserCheck())
	//v2.GET("/info", userInfo.InfoMethod)
	svr.Spin()
}
