mysql:
  host: 124.222.182.66
  port: 3306
  dbname: douyin
  username: root
  password: Wqx1761391865.

redis:
  host: 172.29.64.1
  port: 6379
  Password:
  database: 0

nacos:
  host: 172.29.64.1
  port: 8848

rabbitmq:
  host: 172.29.64.1
  port: 5672
  username: guest
  password: guest

oss:
  bucketName: paigu-douyin-videos
  endpoint: oss-cn-nanjing.aliyuncs.com
  accessKeyId: LTAI5tKz8Jg67pok7LjZ3rus
  accessKeySecret: BUpR46wYSyON68Qpy7aGwEvCSCvzxf