// Code generated by hertz generator.

package router

import (
	userInfo "paigu1902/douyin/service/api-gateway/biz/handler/userInfoPb"
	videoOperator "paigu1902/douyin/service/api-gateway/biz/handler/videoOperatorPb"
	"paigu1902/douyin/service/api-gateway/middlewares"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func Register(r *server.Hertz) {
	v1 := r.Group("/v1")
	v1.POST("/login", userInfo.LoginMethod)
	v1.POST("/register", userInfo.RegisterMethod)
	v2 := r.Group("/v2")
	v2.Use(middlewares.AuthUserCheck())
	v2.GET("/info", userInfo.InfoMethod)

	v3 := r.Group("/v3")
	v3.POST("/action", videoOperator.UploadMethod)
}
