// Code generated by hertz generator.

package userRelationPb

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"paigu1902/douyin/service/api-gateway/biz/rpcClient"
	"paigu1902/douyin/service/rpc-user-relation/kitex_gen/userRelationPb"
)

type MessageHistoryReq struct {
	From_id string
	To_id   string
}

func FollowAction(ctx context.Context, c *app.RequestContext) {}

func FollowList(ctx context.Context, c *app.RequestContext) {}

func FollowerList(ctx context.Context, c *app.RequestContext) {}

func FriendList(ctx context.Context, c *app.RequestContext) {}

func MessageAction(ctx context.Context, c *app.RequestContext) {}

func MessageHistory(ctx context.Context, c *app.RequestContext) {
	req := new(MessageHistoryReq)
	// 1. 绑定校验参数
	if err := c.BindAndValidate(req); err != nil {
		c.JSON(400, err.Error())
		return
	}
	// 2.调用rpc
	resp, err := rpcClient.UserRelationClient.HistoryMessage(ctx, &userRelationPb.HistoryMessageReq{FromId: 123, ToId: 123})
	if err != nil {
		c.JSON(400, err.Error())
		return
	}
	c.JSON(200, resp)
	return
}
