// Code generated by Kitex v0.4.4. DO NOT EDIT.

package videooperator

import (
	server "github.com/cloudwego/kitex/server"
	videoOperatorPb "paigu1902/douyin/service/rpc-video-operator/kitex_gen/videoOperatorPb"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler videoOperatorPb.VideoOperator, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
