// Code generated by Kitex v0.4.4. DO NOT EDIT.
package videooperator

import (
	server "github.com/cloudwego/kitex/server"
	videoOperatorPb "paigu1902/douyin/service/rpc-video-operator/kitex_gen/videoOperatorPb"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler videoOperatorPb.VideoOperator, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
