// Code generated by Kitex v0.4.4. DO NOT EDIT.

package videooperator

import (
	"context"
	"fmt"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
	videoOperatorPb "paigu1902/douyin/service/rpc-video-operator/kitex_gen/videoOperatorPb"
)

func serviceInfo() *kitex.ServiceInfo {
	return videoOperatorServiceInfo
}

var videoOperatorServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "VideoOperator"
	handlerType := (*videoOperatorPb.VideoOperator)(nil)
	methods := map[string]kitex.MethodInfo{
		"Upload": kitex.NewMethodInfo(uploadHandler, newUploadArgs, newUploadResult, false),
		"Feed":   kitex.NewMethodInfo(feedHandler, newFeedArgs, newFeedResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "videoOperatorPb",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func uploadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(videoOperatorPb.VideoUploadReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(videoOperatorPb.VideoOperator).Upload(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *UploadArgs:
		success, err := handler.(videoOperatorPb.VideoOperator).Upload(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UploadResult)
		realResult.Success = success
	}
	return nil
}
func newUploadArgs() interface{} {
	return &UploadArgs{}
}

func newUploadResult() interface{} {
	return &UploadResult{}
}

type UploadArgs struct {
	Req *videoOperatorPb.VideoUploadReq
}

func (p *UploadArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(videoOperatorPb.VideoUploadReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *UploadArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *UploadArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *UploadArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in UploadArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *UploadArgs) Unmarshal(in []byte) error {
	msg := new(videoOperatorPb.VideoUploadReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UploadArgs_Req_DEFAULT *videoOperatorPb.VideoUploadReq

func (p *UploadArgs) GetReq() *videoOperatorPb.VideoUploadReq {
	if !p.IsSetReq() {
		return UploadArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UploadArgs) IsSetReq() bool {
	return p.Req != nil
}

type UploadResult struct {
	Success *videoOperatorPb.VideoUploadResp
}

var UploadResult_Success_DEFAULT *videoOperatorPb.VideoUploadResp

func (p *UploadResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(videoOperatorPb.VideoUploadResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *UploadResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *UploadResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *UploadResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in UploadResult")
	}
	return proto.Marshal(p.Success)
}

func (p *UploadResult) Unmarshal(in []byte) error {
	msg := new(videoOperatorPb.VideoUploadResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UploadResult) GetSuccess() *videoOperatorPb.VideoUploadResp {
	if !p.IsSetSuccess() {
		return UploadResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UploadResult) SetSuccess(x interface{}) {
	p.Success = x.(*videoOperatorPb.VideoUploadResp)
}

func (p *UploadResult) IsSetSuccess() bool {
	return p.Success != nil
}

func feedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(videoOperatorPb.FeedReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(videoOperatorPb.VideoOperator).Feed(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *FeedArgs:
		success, err := handler.(videoOperatorPb.VideoOperator).Feed(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*FeedResult)
		realResult.Success = success
	}
	return nil
}
func newFeedArgs() interface{} {
	return &FeedArgs{}
}

func newFeedResult() interface{} {
	return &FeedResult{}
}

type FeedArgs struct {
	Req *videoOperatorPb.FeedReq
}

func (p *FeedArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(videoOperatorPb.FeedReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *FeedArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *FeedArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *FeedArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in FeedArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *FeedArgs) Unmarshal(in []byte) error {
	msg := new(videoOperatorPb.FeedReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var FeedArgs_Req_DEFAULT *videoOperatorPb.FeedReq

func (p *FeedArgs) GetReq() *videoOperatorPb.FeedReq {
	if !p.IsSetReq() {
		return FeedArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *FeedArgs) IsSetReq() bool {
	return p.Req != nil
}

type FeedResult struct {
	Success *videoOperatorPb.FeedResp
}

var FeedResult_Success_DEFAULT *videoOperatorPb.FeedResp

func (p *FeedResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(videoOperatorPb.FeedResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *FeedResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *FeedResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *FeedResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in FeedResult")
	}
	return proto.Marshal(p.Success)
}

func (p *FeedResult) Unmarshal(in []byte) error {
	msg := new(videoOperatorPb.FeedResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *FeedResult) GetSuccess() *videoOperatorPb.FeedResp {
	if !p.IsSetSuccess() {
		return FeedResult_Success_DEFAULT
	}
	return p.Success
}

func (p *FeedResult) SetSuccess(x interface{}) {
	p.Success = x.(*videoOperatorPb.FeedResp)
}

func (p *FeedResult) IsSetSuccess() bool {
	return p.Success != nil
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Upload(ctx context.Context, Req *videoOperatorPb.VideoUploadReq) (r *videoOperatorPb.VideoUploadResp, err error) {
	var _args UploadArgs
	_args.Req = Req
	var _result UploadResult
	if err = p.c.Call(ctx, "Upload", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Feed(ctx context.Context, Req *videoOperatorPb.FeedReq) (r *videoOperatorPb.FeedResp, err error) {
	var _args FeedArgs
	_args.Req = Req
	var _result FeedResult
	if err = p.c.Call(ctx, "Feed", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
