// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	UserCommPb "paigu1902/douyin/biz/router/UserCommPb"
	userInfoPb "paigu1902/douyin/biz/router/userInfoPb"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	UserCommPb.Register(r)

	userInfoPb.Register(r)
}
