// Code generated by Kitex v0.4.4. DO NOT EDIT.
package userrelation

import (
	server "github.com/cloudwego/kitex/server"
	userRelationPb "paigu1902/douyin/service/rpc-user-relation/kitex_gen/userRelationPb"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler userRelationPb.UserRelation, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
