// Code generated by hertz generator.

package UserCommPb

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"log"
	"paigu1902/douyin/service/api-gateway/biz/rpcClient"
	"paigu1902/douyin/service/rpc-user-operator/rpc-user-comment/kitex_gen/UserCommPb"
	"strconv"
)

type CommentActionReq struct {
	UserId      int64 `query:"user_id"`
	CommentId   int64
	VideoId      int64  `query:"video_id"`
	ActionType  int32  `query:"action_type"`
	CommentText string `vd:"len($)>=0 && len($)<30"`
}

type CommentsInfoReq struct {
	UserId int64 `query:"user_id"`
	VideoId int64 `query:"video_id"`
}

func CommentActionMethod(ctx context.Context, c *app.RequestContext) {
	req := new(CommentActionReq)
	if err := c.BindAndValidate(req); err != nil {
		c.JSON(400, err.Error())
		return
	}
	if req.ActionType == 2 {
		// 删除评论 comment_text = ""
		req.CommentText = ""
		CommentId, isOk := c.GetQuery("comment_id")
		log.Println(req.VideoId, CommentId)
		if !isOk {
			c.JSON(400, "get current comment_id error in delete comment")
			return
		}
		tmp, _ := strconv.Atoi(CommentId)
		req.CommentId = int64(tmp)
	} else {
		// 添加评论 comment_id = 0
		req.CommentId = 0
		CommentText, isOk := c.GetQuery("comment_text")
		log.Println(req.VideoId, req.UserId, CommentText)
		if !isOk {
			c.JSON(400, "get current comment_text error in add comment")
			return
		}
		if len(CommentText) == 0 {
			c.JSON(400, "add_op: the length of comment should not be 0")
			return
		}
		req.CommentText = CommentText
	}

	resp, err := rpcClient.UserComm.CommentAction(ctx, &UserCommPb.DouyinCommentActionRequest{
		UserId:      req.UserId,
		VideoId:     req.VideoId,
		ActionType:  req.ActionType,
		CommentText: req.CommentText,
		CommentId:   req.CommentId,
	})
	if err != nil {
		log.Println("400 le")
		c.JSON(400, err.Error())
		return
	}
	c.JSON(200, &resp)
	return
}

func CommentGetListMethod(ctx context.Context, c *app.RequestContext) {
	req := new(CommentsInfoReq)
	if err := c.BindAndValidate(req); err != nil {
		c.JSON(400, err.Error())
		return
	}
	resp, err := rpcClient.UserComm.GetCommentsByVideo(ctx, &UserCommPb.DouyinCommentListRequest{
		UserId:  req.UserId,
		VideoId: req.VideoId,
	})
	if err != nil {
		c.JSON(400, err.Error())
		return
	}
	c.JSON(200, &resp)
	return
}

func CommentNumberMethod(ctx context.Context, c *app.RequestContext) {
	req := new(CommentsInfoReq)
	if err := c.BindAndValidate(req); err != nil {
		c.JSON(400, err.Error())
		return
	}
	resp, err := rpcClient.UserComm.GetCommentNumberByVideo(ctx, &UserCommPb.DouyinCommentNumberRequest{
		UserId:  req.UserId,
		VideoId: req.VideoId,
	})
	if err != nil {
		c.JSON(400, err.Error())
		return
	}
	c.JSON(200, &resp)
	return
}
