// Code generated by hertz generator.

package videoOperator

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/kitex/client"
	"github.com/kitex-contrib/registry-nacos/resolver"
	"log"
	"paigu1902/douyin/service/rpc-video-operator/kitex_gen/videoOperatorPb"
	"paigu1902/douyin/service/rpc-video-operator/kitex_gen/videoOperatorPb/videooperator"
	"time"
)

func UploadMethod(ctx context.Context, c *app.RequestContext) {
	r, err := resolver.NewDefaultNacosResolver()
	if err != nil {
		panic(err)
	}
	newClient := videooperator.MustNewClient(
		"videoOperatorImpl",
		client.WithResolver(r),
		client.WithRPCTimeout(time.Second*5),
	)
	var req videoOperatorPb.VideoUploadReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}
	resp, err := newClient.Upload(context.Background(), &videoOperatorPb.VideoUploadReq{
		Token: req.Token,
		Data:  req.Data,
		Title: req.Title,
	})
	if err != nil {
		log.Fatal(err)
	}
	log.Println("resp", resp)
	c.JSON(200, resp)
}
