// Code generated by Kitex v0.4.4. DO NOT EDIT.

package userinfo

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	userInfoPb "paigu1902/douyin/service/rpc-user-info/kitex_gen/userInfoPb"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, Req *userInfoPb.RegisterReq, callOptions ...callopt.Option) (r *userInfoPb.RegisterResp, err error)
	Login(ctx context.Context, Req *userInfoPb.LoginReq, callOptions ...callopt.Option) (r *userInfoPb.LoginResp, err error)
	Info(ctx context.Context, Req *userInfoPb.UserInfoReq, callOptions ...callopt.Option) (r *userInfoPb.UserInfoResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserInfoClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserInfoClient struct {
	*kClient
}

func (p *kUserInfoClient) Register(ctx context.Context, Req *userInfoPb.RegisterReq, callOptions ...callopt.Option) (r *userInfoPb.RegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, Req)
}

func (p *kUserInfoClient) Login(ctx context.Context, Req *userInfoPb.LoginReq, callOptions ...callopt.Option) (r *userInfoPb.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, Req)
}

func (p *kUserInfoClient) Info(ctx context.Context, Req *userInfoPb.UserInfoReq, callOptions ...callopt.Option) (r *userInfoPb.UserInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Info(ctx, Req)
}
