// Code generated by Kitex v0.4.4. DO NOT EDIT.

package usercommrpc

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	UserCommPb "paigu1902/douyin/service/rpc-user-operator/rpc-user-comment/kitex_gen/UserCommPb"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	InsertComment(ctx context.Context, Req *UserCommPb.DouyinCommentActionRequest, callOptions ...callopt.Option) (r *UserCommPb.DouyinCommentActionResponse, err error)
	GetCommentsByVideo(ctx context.Context, Req *UserCommPb.DouyinCommentListRequest, callOptions ...callopt.Option) (r *UserCommPb.DouyinCommentListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserCommRpcClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserCommRpcClient struct {
	*kClient
}

func (p *kUserCommRpcClient) InsertComment(ctx context.Context, Req *UserCommPb.DouyinCommentActionRequest, callOptions ...callopt.Option) (r *UserCommPb.DouyinCommentActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.InsertComment(ctx, Req)
}

func (p *kUserCommRpcClient) GetCommentsByVideo(ctx context.Context, Req *UserCommPb.DouyinCommentListRequest, callOptions ...callopt.Option) (r *UserCommPb.DouyinCommentListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCommentsByVideo(ctx, Req)
}
