// Code generated by Kitex v0.4.4. DO NOT EDIT.

package usercommrpc

import (
	server "github.com/cloudwego/kitex/server"
	UserCommPb "paigu1902/douyin/service/rpc-user-operator/rpc-user-comment/kitex_gen/UserCommPb"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler UserCommPb.UserCommRpc, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
